'use client'
import NavBar from '@/components/NavBar'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer'
import Provider from '@/components/Provider'
import localFont from '@next/font/local';
import { Toaster } from "@/components/ui/toaster"
 
const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <Toaster />
      <body className={ inter.className} 
       >
      <Provider>
          <NavBar />
          {children}
        <Footer />
      </Provider>
      </body>
    </html>
  )
}

